[package]
name = "backend"
version = "1.2.0"
edition = "2024"
license = "blessing"

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8", features = ["multipart"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "fs"] }
http = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = [ "runtime-tokio", "tls-native-tls", "sqlite", "chrono", "migrate" ] }
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
serde_qs = "0.15.0"
reqwest = { version = "0.13.1" }
serde_json = "1.0.149"
base64      = "0.22"
hmac = "0.12.1"
libc = "0.2"
sha2 = "0.10.9"
hex = "0.4.3"
chrono = "0.4.43"
subtle = "2.6.1"
tera = "1.20.1"
percent-encoding = "2.3.2"
figment = { version = "0.10.19", features = ["env", "toml"] }
email_address = "0.2.9"
resend-rs = "0.21.1"
mime_guess = "2"

[dev-dependencies]
tempfile = "3"
